apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-services-app-deployment
  labels:
    app: k8s-microservices-deploy-example
spec:
  replicas: 2
  selector:
    matchLabels:
      name: notification-services-app-pod
      app: k8s-microservices-deploy-example
  template:
    metadata:
      name: notification-services-app-pod
      labels:
        name: notification-services-app-pod
        app: k8s-microservices-deploy-example

    spec:
      containers:
      - name: notification-services-app
        image: oktydag/notification-services-app:1.0
        ports:
        - containerPort: 80