apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: k8s-microservices-deploy-example
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-pod
    app: k8s-microservices-deploy-example