apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: k8s-microservices-deploy-example
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-pod
      app: k8s-microservices-deploy-example
  template:
    metadata:
      name: redis-pod
      labels:
        name: redis-pod
        app: k8s-microservices-deploy-example

    spec:
      containers:
      - name: redis
        image: redis
        ports:
        - containerPort: 6379